name: Deploy to EC2
env:
  NAME_OF_PRIVATE_KEY: "elad_ca-central-1.pem"
  EC2_PUBLIC_IP: "3.96.54.15" 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get install -y openssh-client

    - name: mkdir .ssh and copy private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
        chmod 600 ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }}
        ls -la ~/.ssh
        pwd
      
    - name: Copy file to EC2
      run: |
        ls -la ~/.ssh
        scp -i ~/.ssh/${{ env.NAME_OF_PRIVATE_KEY }} index.html ubuntu@${{ env.EC2_PUBLIC_IP }}:/home/ubuntu/
      # Replace 'index.html' with the appropriate file name and '/home/ubuntu/' with the desired directory path on EC2

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pwd
          ls -la
          sudo apt update
          sudo apt install -y apache2
