name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy index.html to EC2
      run: scp -i ${{ secrets.EC2_SSH_KEY }} index.html ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/html/
